### PR TITLE
Fix a11y errors

### PR DESCRIPTION
**Pull request by lc512k**
enforces pa11y checks

@GlynnPhillips I've used the `true-client-ip` header for these tests, though couldn't quite get `barriers/corporate-prospect-trial` to load locally

cc @pixelandpage

### CODE REVIEW

**Comment by GlynnPhillips** [comment]
💯 Looks good and thanks

**Comment by GlynnPhillips** [comment]
I think @paddyo might be the best person to help with the corporate-prospect-trial barrier

**Comment by paddyo** [comment]
This took out the corporate prospect barrier, I've pushed a hot fix.

**Comment by lc512k** [comment]
@paddyo what broke it exactly?

**Pull request merged**
